### ISSUE TITLE
Suspicious Code

### ISSUE THREAD

**Issue by felixguendling** [motis-project/nigiri#121]
Every real-time trip will be taken - no matter the start time is in the interval or not:

https://github.com/motis-project/nigiri/blob/3726dafaa22df840796b0f768966fd6f709b155b/src/routing/start_times.cc#L152-L155

Should probably be destination match mode:

https://github.com/motis-project/nigiri/blob/3726dafaa22df840796b0f768966fd6f709b155b/src/routing/dijkstra.cc#L45

**Comment by felixguendling** [comment]
@mority Solved with the merge?

**Comment by mority** [comment]
> @mority Solved with the merge?

Yes.
