### ISSUE TITLE
36Go log file

### ISSUE THREAD

**Issue by laem** [motis-project/nigiri#123]
My motis/data/log/nigiri.txt file is 36 Go. That's, huge, I wasn't expecting this and my server got out of disk space :sweat_smile: .

I wonder if I'm the only one getting this kind of log size ? 

The file's last 10 000 lines are all similar : 

> 2024-08-05T20:02:00Z | [error][loader.gtfs.services          ] date 2025-12-25 00:00 for service 94504|238309|0 out of range [tt_interval=[2024-07-31 00:00, 2024-08-08 00:00[, calendar=[2024-11-01 00:00, 2024-11-02 00:00[, iterating=[2024-11-01 00:00, 2024-08-08 00:00[]

**Comment by felixguendling** [comment]
Yes, we also have that. I guess the best option would be to remove the log statement. It has been useful to debug issues with datasets where services have all days set to `1` in `calendar.txt` and no exceptions but it doesn't appear on the map or in the routing. Then often the reason was that the GTFS interval didn't overlap the selected timetable interval.

**Comment by felixguendling** [comment]
You can open a PR removing those lines:

https://github.com/motis-project/nigiri/blob/22e62a7e59dcac2b1f494d4a3c46f65209e02d77/src/loader/gtfs/services.cc#L21-L25

**Comment by laem** [comment]
Thanks ! Could they be placed under the condition of a debug mode in the options ?

**Comment by felixguendling** [comment]
For now it's enough to just remove those lines.

Overall I think it would make sense to have some kind of structured (e.g. JSON) log that contains all problems found/fixed/ignored (such as dangling references, trips with less than 2 stops, etc.) + a UI that displays this information in a way so you can filter issues by type, dataset, etc. I know there are already feed validation tools (at least for GTFS, not sure what's the state for NeTEx) for this kind of job. However, I'm not sure if they can scale to the number/size of feeds MOTIS can load with reasonable processing time.

**Comment by felixguendling** [comment]
My guess would be that there is already external logging/log aggregation software that can do this very efficiently. MOTIS is not the first program that produces repetitive log messages. Probably not worth it to implement it in nigiri if there are already good log aggregation solutions that can do the same thing.
