### ISSUE TITLE
GTFS RT - Integration failed with `stop_idx_` assertion fail

### ISSUE THREAD

**Issue by gadcam** [motis-project/nigiri#143]
Got get_location_idx() const: Assertion `fr_->size() > stop_idx_' failed
Here are the logs
```
[info][2024-10-08T05:41:39Z+0000][nigiri.cc:444] us-ri-RIPTA: total_entities=1, trip_resolve_error=1 (100%)
motis: /home/ubuntu/motis/motis/deps/nigiri/src/rt/frun.cc:57: location_idx_t nigiri::rt::frun::run_stop::get_location_idx() const: Assertion `fr_->size() > stop_idx_' failed
````
Link to the assertion
https://github.com/motis-project/nigiri/blob/4b9736b02a91c733041ad11b48ca46b1178a5d4a/src/rt/frun.cc#L57

Happened with
- nigiri d6e1c8f5c0a8264e568fa85a34622e105a975315
- MOTIS v0.12.14  577da282f3703b59675aafd46fd61f942f9683cc

The error appeared after ~9h our of runtime and many integrated feeds so not sure how to provide a minimal reproducible example.
Do not hesitate to tell me what can I share to help investigate.

**Comment by felixguendling** [comment]
Do you have a stack trace or can you run MOTIS with `gdb --args ./motis config.ini` (or however you start MOTIS)?

**Comment by felixguendling** [comment]
Did you run MOTIS with assertions enabled on purpose? If you want to operate, the `Release` build type or `RelWithDebInfo` makes more sense.
